# Generated by Django 3.1.7 on 2021-08-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
